# Generated by Django 6.0.2 on 2026-03-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='projectauthor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='audiences',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='projecttechnology',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissions',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technologies'),
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectTechnology', to='projects.technologies'),
        ),
        migrations.AddField(
            model_name='updates',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updates',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.projects'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcategory',
            unique_together={('project', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='projectauthor',
            unique_together={('project', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='audiences',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttechnology',
            unique_together={('project', 'technology')},
        ),
    ]
