# Generated by Django 6.0.2 on 2026-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='stage',
            field=models.CharField(db_index=True, default='EA', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
