# Generated by Django 6.0.2 on 2026-03-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_stage_alter_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
