# Generated by Django 6.0.2 on 2026-03-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_authors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
