# Generated by Django 6.0.2 on 2026-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='cover_image_url',
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
