# Generated by Django 6.0.2 on 2026-03-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projects_cover_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='stage',
            field=models.CharField(db_index=True, default='Early', max_length=100),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
