# Generated by Django 6.0.2 on 2026-03-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projects_stage_alter_submissions_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiences',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences_set', to='projects.projects'),
        ),
        migrations.CreateModel(
            name='ProjectAudiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.audiences')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'verbose_name': 'Project Audience',
                'verbose_name_plural': 'Project Audiences',
                'unique_together': {('project', 'audience')},
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='audiences',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectAudiences', to='projects.audiences'),
        ),
    ]
