# Generated by Django 6.0.2 on 2026-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_authors_name_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='audiences',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectAudiences', to='projects.audiences'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='authors',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectAuthor', to='projects.authors'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectCategory', to='projects.categories'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectTechnology', to='projects.technologies'),
        ),
    ]
