# Generated by Django 6.0.2 on 2026-04-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projects_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='likes_count',
            new_name='artificial_view',
        ),
    ]
