# Generated by Django 6.0.2 on 2026-04-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_likes_count_projects_artificial_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='audiences',
        ),
    ]
