# Generated by Django 6.0.2 on 2026-04-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projects_audiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='technologies',
        ),
    ]
