# Generated by Django 6.0.2 on 2026-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projects_authors_remove_projects_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='categories',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectCategory', to='projects.categories'),
        ),
    ]
