# Generated by Django 6.0.2 on 2026-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projects_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='authors',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectAuthor', to='projects.authors'),
        ),
    ]
