# Generated by Django 6.0.2 on 2026-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projects_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectaudiences',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectaudiences',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(db_index=True, related_name='projects', through='projects.ProjectTechnology', to='projects.technologies'),
        ),
        migrations.RemoveField(
            model_name='projectaudiences',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='projectaudiences',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectaudiences',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='projectaudiences',
            name='project',
        ),
        migrations.DeleteModel(
            name='Audiences',
        ),
    ]
