# Generated by Django 6.0.2 on 2026-04-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_projectaudiences_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAudiences',
        ),
    ]
