# Generated by Django 6.0.2 on 2026-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_delete_projectaudiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='audiences',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
