# Generated by Django 6.0.2 on 2026-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projects_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
