# Generated by Django 6.0.2 on 2026-04-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projects_is_archived_projects_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='technologies',
            name='type',
        ),
    ]
